name: Build APK for Kivy

on:
  push:
    branches:
      - campo_minado_prof_pronto  
  workflow_dispatch:  # Adiciona a opção para disparar o workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest  # Usando uma máquina com o sistema Ubuntu, que é ideal para o Kivy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Faz checkout do código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # A versão do Python que você está usando

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-dev build-essential git libssl-dev libffi-dev libsqlite3-dev libjpeg-dev liblcms2-dev zlib1g-dev libfreetype6-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        pip install kivy buildozer  # Instala o Kivy e o Buildozer

    - name: Build APK
      run: |
        buildozer android debug  # Gera um APK de debug, você pode usar 'release' para um APK final

    - name: Upload APK as artifact  # Faz o upload do APK gerado para o GitHub Actions
      uses: actions/upload-artifact@v2
      with:
        name: campo_minado_apk
        path: bin/*.apk  # Caminho onde o APK gerado será salvo
